### ISSUE TITLE
omg run appends 'command' to docker's entrypoint

### ISSUE THREAD

**Issue by wilzbach** [microservices/omg#172]
How to reproduce:

```
git clone -b init https://github.com/wilzbach/hashes
```

Works with docker:

```
> docker build -t omg-hashes .
...
> docker run --rm -ti -p 8080:8080 omg-hashes
[main(----) INF] Listening for requests on http://0.0.0.0:8080/
Vibe was run as root, and no user/group has been specified for privilege lowering. Running with full permissions.
```

Fails with OMG:

```
> omg run digest -a method=sha1 -a data=foo
...
✖ Health check failed
  Docker logs:
*Unrecognized command line option: /hashes

XWarning (thread: main): leaking eventcore driver because there are still active handles
   FD 7 (streamListen)
XWarning (thread: main): leaking eventcore driver because there are still active handles
   FD 7 (streamListen)
```

You just need to spawn the `/hashes` executable. It's fully statically linked runs on any Linux >= 2.6.

In case `hooks/pre-build` fails or it takes too long, here's the binary:

[hashes.zip](https://github.com/microservices/omg-cli/files/3043352/hashes.zip)

BTW in the omg log output there only seems to be `stderr`, no `stdout`.

See also: https://github.com/microservice/hashes/pull/1

**Comment by judepereira** [comment]
This is strange, since the omg just calls docker build.

**Comment by wilzbach** [comment]
This is was also appearing here: https://github.com/microservices/d

The solution was to do this:

```
lifecycle:
  startup:
    command: []
```

I always thought that `command` overwrite the Docker entrypoint, but obviously it doesn't, but calls the entrypoint with these arguments. I guess it worked so far, because all other services don't check their arguments and everyone defined the entrypoint properly.

**Comment by Arinono** [comment]
Was fixed without knowing when I removed the last use of `shelljs` for dockerode
