### ISSUE TITLE
subscribe: stop needs to wait until 'unsubscribe' returned

### ISSUE THREAD

**Issue by wilzbach** [microservices/omg#182]
tl;dr: the CLI should properly unsubscribe before quitting.

```
> omg subscribe listen heartbeat
✔ Ran action: `listen` with output: 
✔ Subscribed to event: `heartbeat` data will be posted to this terminal window when appropriate
{
  "eventType": "heartbeat",
  "type": "com.microservices.node.template",
  "specversion": "0.2",
  "source": "/foo",
  "id": "NODE-TEMPLATE-0",
  "time": "2019-04-06T18:33:30.629Z",
  "datacontenttype": "application/json",
  "data": {
    "user": "max",
    "time": "Sat Apr 06 2019 18:33:30 GMT+0000 (Coordinated Universal Time)"
  }
}
✔ Stopped Docker container: 4fb1bacd9095
```

```
> docker logs
Listening on localhost:8080
[subscribe] id:'00d49013-9604-4e07-b5e0-e38208e545f2', endpoint:'http://host.docker.internal:12289', name:'heartbeat', data:  {}
[publish] 'heartbeat' payload:  { user: 'max',
  time:
   'Sat Apr 06 2019 18:33:30 GMT+0000 (Coordinated Universal Time)' }
```

(no unsubscribe action was called)

It is vital that the container runs through the unsubscription phase as it e.g. might have contacted external APIs or hopefully soon `omg subscribe` can attach to running containers.

**Comment by Arinono** [comment]
Can you provide the project you used in order to reproduce. It should be already unsubscribing before quitting via `Ctrl+C` (see https://github.com/microservices/omg/blob/9b10ed3d67b3c40324172a99542bbcbdc76cf0ea/src/cli/Cli.ts#L368-L370)

Did you quit using another way, or was it due to an error ?

**Comment by wilzbach** [comment]
Sorry, I used this project: https://github.com/microservices/node-events

> It should be already unsubscribing before quitting via Ctrl+C (see

Well, it was never called.

> Did you quit using another way, 

Ctrl-C

**Comment by Arinono** [comment]
It looks like you forgot to add the `unsubscribe` part in your `microservice.yml`.
https://github.com/microservices/node-events/blob/afed20be65e6ae13f1f13ca69693864dde75603e/microservice.yml#L21-L24

I tried adding it to your service, but another error shows up (one I don't know how to debug). But after trying with the slack service, adding `unsubscribe` to the `microservice.yml` makes the cli call this endpoint before killing the service/container.

I you need to reopen this issue, feel free to do so 😃
