### ISSUE TITLE
Favicon and title

### ISSUE THREAD

**Issue by stevepeak** [microservices/omg#195]
Change the favicon and page title to the OMG logo and title of `Open Microservice Guide`

<img width="251" alt="Screen Shot 2019-05-14 at 10 45 57" src="https://user-images.githubusercontent.com/2041757/57684129-77fe2780-7635-11e9-83c1-0b7e0ec53ee9.png">

**Comment by Arinono** [comment]
Fixed with 31042fe993d6188eb92732f3c1b7e8a723d60682
