### ISSUE TITLE
Make 'omg list' or similar

### ISSUE THREAD

**Issue by kenneth-reitz** [microservices/omg#197]
The idea is that this command would list all of the available actions for a given microservice.

**Comment by Arinono** [comment]
Added `omg list` command. Available flags are `- j --json` in order to get raw json for all actions and `-d --details` for detailed actions (http paths and ports, ...). Released in `omg@beta` (v0.12.0).

Feel free to reopen if you find issues :)

**Comment by kenneth-reitz** [comment]
nice!

**Comment by kenneth-reitz** [comment]
:sparkles: :cake: :sparkles:
