### ISSUE TITLE
healthcheck regression: default URL detection is faulty

### ISSUE THREAD

**Issue by wilzbach** [microservices/omg#227]
0.13.6 just blocks on microservices without a `health` config, e.g.

Example:

https://github.com/omg-services/hashes

```
omg run hmac -a method=sha1 -a "data=hello world" -a "secret=my secret"
ℹ Building Docker image
Step 1/9 : FROM dlang2/ldc-ubuntu:1.14.0 as builder
---> 5961d5b8c51d
Step 2/9 : WORKDIR /src
---> Using cache
---> cfd36685387e
Step 3/9 : COPY dub.sdl dub.selections.json /src/
---> Using cache
---> 3f62f5a3c0df
Step 4/9 : RUN dub build -b release || true
---> Using cache
---> 0bf68fc92a00
Step 5/9 : COPY source /src/source
---> Using cache
---> eb61040f30ec
Step 6/9 : RUN dub build -b release
---> Using cache
---> dec67e43db43
Step 7/9 : FROM scratch
--->
Step 8/9 : COPY --from=builder /src/hashes /hashes
---> Using cache
---> 7dcf87af35dc
Step 9/9 : ENTRYPOINT [ "/hashes" ]
---> Using cache
---> 09af64ddb039
Successfully built 09af64ddb039
Successfully tagged omg/wilzbach/hashes:latest
✔ Built Docker image with name: omg/wilzbach/hashes
✔ Started Docker container: 76a2fd0b6d0d
  Executing default health check
```

So I presume it checks sth. wrong on the default healthcheck. It works if I add an explicit health check part. If the default detection is so error-prone, we need to require the user to add.

**Comment by wilzbach** [comment]
For reference I had to add this https://github.com/microservices/omg/issues/227

**Comment by Arinono** [comment]
I agree with you that we need to require the user to use the 'proper' health check. The default one should be temporary, waiting for the engine and all the services to be compliant.
I will still fix this one obviously 😉

**Comment by wilzbach** [comment]
I also had to add it for the YAML repo: https://github.com/omg-services/yaml/pull/4

**Comment by wilzbach** [comment]
And for the Python service PSQL it's not working entirely: https://github.com/omg-services/psql/pull/4
Can we print the URL of the healthcheck point, response status and response message (if available) when the health check fails?
