### ISSUE TITLE
[regression] omg now waits several seconds after Docker shutdown

### ISSUE THREAD

**Issue by wilzbach** [microservices/omg#228]
```
✔ Ran action: `hmac` with output: {
  "method": "sha1",
  "digest": "9F60EE4B05E590A7F3FAC552BFB9D98FA46F78D9"
}
✔ Stopped Docker container: f793781f4126
```

After the last line, `omg` halts for about 3-5 seconds before finally terminating. Is it doing additional health checks?

**Comment by Arinono** [comment]
Honestly I don't know what's happening, I will have to take a look. At first I thought it was waiting for something from the version checking, but, after debugging, it's already done by far at this point.

**Comment by wilzbach** [comment]
Here's how this looks on my machine:

https://asciinema.org/a/LF1vVm5ObzeIkf1pHWE5Ny45I

**Comment by wilzbach** [comment]
Another example with a different service:

   https://asciinema.org/a/eu0metBucWTXuKVxhGKSOLR21
