### ISSUE TITLE
getOpenPort might return a blocked port

### ISSUE THREAD

**Issue by wilzbach** [microservices/omg#260]
https://github.com/microservices/omg/blob/4b0d646d0c442e9595df814dfe438917e2fc32da/packages/omg/src/commands/Subscribe.ts#L54-L55

tl;dr: the returned port might have been taken by another program in the mean time. This should be handled with at least a graceful few retries.
I know this small deadlock isn't a huge problem, but the more OMG gets used, the higher the chances of users running into this.

**Comment by Arinono** [comment]
Correct me if I'm wrong, but the `.getOpenPort()` calls `.getPort()`, which, on fail, calls itself again (see line 371)

https://github.com/microservices/omg/blob/67b23fad432ead9d2f26b4e7a06bf3dbf2ace32d/packages/omg/src/utils.ts#L349-L375

**Comment by wilzbach** [comment]
Yes, but my point was that while you detected a port to be free, it is possible that before you managed to block it by listening another app used that port.

**Comment by StoryscriptHuman** [comment]
Closing as fixed in new dawn releases
