### ISSUE TITLE
add help property to forwards

### ISSUE THREAD

**Issue by Arinono** [microservices/omg#264]
In order to match the [documentation](https://deploy-preview-78--microservice-guide.netlify.com/schema/forwards/#http), we need to add the support for help (with is optionnal) in the [schema](https://github.com/microservices/omg/blob/ec11b21b0757aa3f2e9f7851878fd2257211336c/packages/omg-validate/src/schema/schemas/forward.ts#L3)

We also need to add this help field inside the `forwards` view in the OMG APP

**Comment by StoryScriptAI** [comment]
Just checked and verified this is done in https://github.com/microservices/omg/pull/270

**Comment by StoryscriptHuman** [comment]
Closing as implemented in new dawn releases
