### ISSUE TITLE
refactor(forwards): change forward to forwards

### ISSUE THREAD

**Issue by Arinono** [microservices/omg#271]
In order to match the [documentation](https://microservice.guide/schema/forwards/), and the runtime implementation, we need to change `forward` to `forwards` in [`omg-validate` schema](https://github.com/microservices/omg/blob/ec11b21b0757aa3f2e9f7851878fd2257211336c/packages/omg-validate/src/schema/schemas/microservice.ts#L138)

Once closed and released, ping me or @JeanBarriere to update [microservice-validate](https://github.com/arinono/microservice-validate)

**Comment by StoryScriptAI** [comment]
This is already done in https://github.com/microservices/omg/pull/270

**Comment by JeanBarriere** [comment]
@StoryScriptAI just to make sure, is it done in the alpha release of the CLI ?

**Comment by StoryScriptAI** [comment]
Yes, this is fixed in v1.0.0-alpha1

**Comment by StoryscriptHuman** [comment]
Closing as fixed
