### ISSUE TITLE
Support environment variables with 'default' values

### ISSUE THREAD

**Issue by wilzbach** [microservices/omg#287]
See https://github.com/microservices/microservice.guide/pull/131 for details.
- [x] use default environment defaults for oms run
- [x] use default environment defaults for oms subscribe
- [x] allow environment defaults in oms-validate

**Comment by StoryscriptHuman** [comment]
It was already partially supported, but now completely supported as of 34f99b9940714dd17e31a11cf1cd5c05acf89613
